#====================
#VISUALIZATION
#====================
/vis/open OGLIQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 60 30
/vis/viewer/zoom 3
/vis/viewer/set/style surface
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/endOfEventAction accumulate -4

#====================
#====================
#SET MATERIALS
#====================
/gate/geometry/setMaterialDatabase GateMaterials.db

#====================
# WORLD
#====================
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm

#====================
# PORTAMUESTRA (cuerpo del cilindro)
#====================
/gate/world/daughters/name portamuestra
/gate/world/daughters/insert cylinder
/gate/portamuestra/setMaterial Aluminium
/gate/portamuestra/vis/setColor white
/gate/portamuestra/geometry/setRmax 74. mm
/gate/portamuestra/geometry/setRmin 73.75 mm
/gate/portamuestra/geometry/setHeight 199.5 mm
/gate/portamuestra/placement/setRotationAxis 1 0 0
/gate/portamuestra/placement/setRotationAngle 90 deg
/gate/portamuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA PORTAMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapaportamuestra
/gate/world/daughters/insert cylinder
/gate/tapaportamuestra/setMaterial Aluminium
/gate/tapaportamuestra/vis/setColor white
/gate/tapaportamuestra/geometry/setRmax 74. mm
/gate/tapaportamuestra/geometry/setRmin 0. mm
/gate/tapaportamuestra/geometry/setHeight 0.5 mm
/gate/tapaportamuestra/placement/setRotationAxis 1 0 0
/gate/tapaportamuestra/placement/setRotationAngle 90 deg
/gate/tapaportamuestra/placement/setTranslation 0. -99.75 0. mm
/gate/tapaportamuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# CONTENEDOR DE MUESTRA 
#====================
/gate/world/daughters/name contenedormuestra
/gate/world/daughters/insert cylinder
/gate/contenedormuestra/setMaterial PVC
/gate/contenedormuestra/vis/setColor cyan
/gate/contenedormuestra/geometry/setRmax 50.97 mm
/gate/contenedormuestra/geometry/setRmin 50.47 mm
/gate/contenedormuestra/geometry/setHeight 129.5 mm
/gate/contenedormuestra/placement/setRotationAxis 1 0 0
/gate/contenedormuestra/placement/setRotationAngle 90 deg
/gate/contenedormuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapacontenedorsup
/gate/world/daughters/insert cylinder
/gate/tapacontenedorsup/setMaterial PVC
/gate/tapacontenedorsup/vis/setColor cyan
/gate/tapacontenedorsup/geometry/setRmax 62.63 mm
/gate/tapacontenedorsup/geometry/setRmin 61.63 mm
/gate/tapacontenedorsup/geometry/setHeight 20.8 mm
/gate/tapacontenedorsup/placement/setRotationAxis 1 0 0
/gate/tapacontenedorsup/placement/setRotationAngle 90 deg
/gate/tapacontenedorsup/placement/setTranslation 0. 75.15 0. mm
/gate/tapacontenedorsup/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA PARA LA TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapasup
/gate/world/daughters/insert cylinder
/gate/tapasup/setMaterial PVC
/gate/tapasup/vis/setColor cyan
/gate/tapasup/geometry/setRmax 62.63 mm
/gate/tapasup/geometry/setRmin 0. mm
/gate/tapasup/geometry/setHeight 0.2 mm
/gate/tapasup/placement/setRotationAxis 1 0 0
/gate/tapasup/placement/setRotationAngle 90 deg
/gate/tapasup/placement/setTranslation 0. 64.76 0. mm
/gate/tapasup/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA CONTENEDORMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapacontenedormuestra
/gate/world/daughters/insert cylinder
/gate/tapacontenedormuestra/setMaterial PVC
/gate/tapacontenedormuestra/vis/setColor cyan
/gate/tapacontenedormuestra/geometry/setRmax 50.97 mm
/gate/tapacontenedormuestra/geometry/setRmin 0. mm
/gate/tapacontenedormuestra/geometry/setHeight 0.5 mm
/gate/tapacontenedormuestra/placement/setRotationAxis 1 0 0
/gate/tapacontenedormuestra/placement/setRotationAngle 90 deg
/gate/tapacontenedormuestra/placement/setTranslation 0. -64.75 0. mm
/gate/tapacontenedormuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE TUBOS (con agujeros) 
#====================
/gate/world/daughters/name soportetubos
/gate/world/daughters/insert cylinder
/gate/soportetubos/setMaterial Polypropilene
/gate/soportetubos/vis/setColor red
/gate/soportetubos/geometry/setRmax 50.965 mm
/gate/soportetubos/geometry/setRmin 0. mm
/gate/soportetubos/geometry/setHeight 25. mm
/gate/soportetubos/placement/setRotationAxis 1 0 0
/gate/soportetubos/placement/setRotationAngle 90 deg
/gate/soportetubos/placement/setTranslation 0. -12.5 0. mm
/gate/soportetubos/vis/forceWireframe
/gate/geometry/rebuild

#====================
#GEOMETRY-CIRCULO MEDIO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulomedio
/gate/world/daughters/insert cylinder
/gate/circulomedio/setMaterial Polypropilene  
/gate/circulomedio/vis/setColor red           
/gate/circulomedio/geometry/setRmax 9.6 mm
/gate/circulomedio/geometry/setRmin 9.55 mm
/gate/circulomedio/geometry/setHeight 25. mm
/gate/circulomedio/placement/setRotationAxis 1 0 0
/gate/circulomedio/placement/setRotationAngle 90 deg
/gate/circulomedio/placement/setTranslation 0. -12.5 0. mm
/gate/circulomedio/vis/forceWireframe              
/gate/circulomedio/vis/setVisible true
/gate/geometry/rebuild  

#====================
#GEOMETRY-CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circuloexterno
/gate/world/daughters/insert cylinder
/gate/circuloexterno/setMaterial Polypropilene  
/gate/circuloexterno/vis/setColor red           
/gate/circuloexterno/geometry/setRmax 9.6 mm
/gate/circuloexterno/geometry/setRmin 9.55 mm
/gate/circuloexterno/geometry/setHeight 25. mm
/gate/circuloexterno/placement/setRotationAxis 1 0 0
/gate/circuloexterno/placement/setRotationAngle 90 deg
/gate/circuloexterno/placement/setTranslation 39. -12.5 0. mm
/gate/circuloexterno/vis/forceWireframe              
/gate/circuloexterno/vis/setVisible true
/gate/geometry/rebuild

#====================
# REPEAT-CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circuloexterno/repeaters/insert ring
/gate/circuloexterno/ring/setRepeatNumber 12
/gate/circuloexterno/ring/setPoint1 0. 1. 0. mm
/gate/circuloexterno/ring/setPoint2 0. 0. 0. mm
/gate/circuloexterno/ring/disableAutoRotation
/gate/circuloexterno/vis/forceWireframe
/gate/geometry/rebuild

#====================
#GEOMETRY-CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulointerno
/gate/world/daughters/insert cylinder
/gate/circulointerno/setMaterial Polypropilene  
/gate/circulointerno/vis/setColor red           
/gate/circulointerno/geometry/setRmax 9.6 mm
/gate/circulointerno/geometry/setRmin 9.55 mm
/gate/circulointerno/geometry/setHeight 25. mm
/gate/circulointerno/placement/setRotationAxis 1 0 0
/gate/circulointerno/placement/setRotationAngle 90 deg
/gate/circulointerno/placement/setTranslation 18.5 -12.5 11. mm
/gate/circulointerno/vis/forceWireframe              
/gate/geometry/rebuild

#====================
# REPEAT-CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circulointerno/repeaters/insert ring
/gate/circulointerno/ring/setRepeatNumber 6
/gate/circulointerno/ring/setPoint1 0. 1. 0. mm
/gate/circulointerno/ring/setPoint2 0. 0. 0. mm
/gate/circulointerno/ring/disableAutoRotation
/gate/circulointerno/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 1
#====================
/gate/world/daughters/name soportemadera1
/gate/world/daughters/insert cylinder
/gate/soportemadera1/setMaterial Wood
/gate/soportemadera1/vis/setColor yellow
/gate/soportemadera1/geometry/setRmax 55.5 mm
/gate/soportemadera1/geometry/setRmin 0. mm
/gate/soportemadera1/geometry/setHeight 9. mm
/gate/soportemadera1/placement/setRotationAxis 1 0 0
/gate/soportemadera1/placement/setRotationAngle 90 deg
/gate/soportemadera1/placement/setTranslation 0. -69.25 0. mm
/gate/soportemadera1/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 2
#====================
/gate/world/daughters/name soportemadera2
/gate/world/daughters/insert box
/gate/soportemadera2/setMaterial Wood
/gate/soportemadera2/vis/setColor yellow
/gate/soportemadera2/geometry/setXLength 30. mm
/gate/soportemadera2/geometry/setYLength 30. mm
/gate/soportemadera2/geometry/setZLength 15. mm
/gate/soportemadera2/placement/setRotationAxis 1 0 0
/gate/soportemadera2/placement/setRotationAngle 90 deg
/gate/soportemadera2/placement/setTranslation 0. -81.5 0. mm
/gate/soportemadera2/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 3
#====================
/gate/world/daughters/name soportemadera3
/gate/world/daughters/insert cylinder
/gate/soportemadera3/setMaterial Wood
/gate/soportemadera3/vis/setColor yellow
/gate/soportemadera3/geometry/setRmax 55.5 mm
/gate/soportemadera3/geometry/setRmin 0. mm
/gate/soportemadera3/geometry/setHeight 9. mm
/gate/soportemadera3/placement/setRotationAxis 1 0 0
/gate/soportemadera3/placement/setRotationAngle 90 deg
/gate/soportemadera3/placement/setTranslation 0. -93.45 0. mm
/gate/soportemadera3/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SYSTEM - scanner
#====================
/gate/world/daughters/name scanner
/gate/world/daughters/insert cylinder
/gate/scanner/setMaterial Air
/gate/scanner/vis/setColor yellow
/gate/scanner/geometry/setRmax 9.55 mm
/gate/scanner/geometry/setRmin 0. mm
/gate/scanner/geometry/setHeight 107.5 mm
/gate/scanner/placement/setRotationAxis 1 0 0
/gate/scanner/placement/setRotationAngle 90 deg
/gate/scanner/vis/forceWireframe
/gate/geometry/rebuild

#====================
#TAPA- tapa del tubo 
#====================
/gate/scanner/daughters/name tapa
/gate/scanner/daughters/insert cylinder
/gate/tapa/setMaterial Polypropilene
/gate/tapa/vis/setColor white
/gate/tapa/geometry/setRmax 9.5 mm
/gate/tapa/geometry/setRmin 7.5 mm
/gate/tapa/geometry/setHeight 15.5 mm
/gate/tapa/placement/setTranslation 0 0 -44 mm
/gate/tapa/vis/forceWireframe
/gate/geometry/rebuild

#====================
#FIRST LEVEL OF THE SYSTEM-tubo Fricke
#====================
/gate/scanner/daughters/name tubo
/gate/scanner/daughters/insert cylinder
/gate/tubo/setMaterial Glass
/gate/tubo/vis/setColor gray
/gate/tubo/geometry/setRmax 8.5 mm
/gate/tubo/geometry/setRmin 7.5 mm
/gate/tubo/geometry/setHeight 87. mm
/gate/tubo/placement/setTranslation 0 0 9.7 mm
/gate/tubo/vis/forceWireframe
/gate/geometry/rebuild

#====================
#SECOND LEVEL OF THE SYSTEM-aguatubo Fricke (la altura 56.74 mm es acorcde a Volumen de 10 mL de agua)
#====================
/gate/tubo/daughters/name aguafricke
/gate/tubo/daughters/insert cylinder
/gate/aguafricke/setMaterial Water
/gate/aguafricke/vis/setColor blue
/gate/aguafricke/geometry/setRmax 7.49 mm
/gate/aguafricke/geometry/setRmin 0. mm
/gate/aguafricke/geometry/setHeight 56.74 mm
/gate/aguafricke/placement/setTranslation 0 0 15. mm
/gate/aguafricke/vis/forceWireframe
/gate/geometry/rebuild

#====================
#ATTACH VOLUMES TO A SYSTEM
#====================
/gate/systems/scanner/level1/attach tapa
/gate/systems/scanner/level1/attach tubo
/gate/systems/scanner/level2/attach aguafricke

#====================
#DEFINE A SENSITIVE DETECTOR
#====================
/gate/aguafricke/attachCrystalSD

#====================
#GEOMETRY-Parte superior RACK (sin agujeros)
#====================
/gate/world/daughters/name racksup
/gate/world/daughters/insert cylinder
/gate/racksup/setMaterial StainlessSteel  
/gate/racksup/vis/setColor gray           
/gate/racksup/geometry/setRmax 85.5 mm
/gate/racksup/geometry/setRmin 75.5 mm
/gate/racksup/geometry/setHeight 1. mm
/gate/racksup/placement/setRotationAxis 1 0 0
/gate/racksup/placement/setRotationAngle 90 deg
/gate/racksup/placement/setTranslation 0. 101. 0. mm
/gate/racksup/vis/forceWireframe              
/gate/racksup/vis/setVisible true
/gate/geometry/rebuild 

#====================
#GEOMETRY-Parte inferior RACK (sin agujeros)
#====================
/gate/world/daughters/name rackinf
/gate/world/daughters/insert cylinder
/gate/rackinf/setMaterial StainlessSteel  
/gate/rackinf/vis/setColor gray           
/gate/rackinf/geometry/setRmax 85.5 mm
/gate/rackinf/geometry/setRmin 75.5 mm
/gate/rackinf/geometry/setHeight 1. mm
/gate/rackinf/placement/setRotationAxis 1 0 0
/gate/rackinf/placement/setRotationAngle 90 deg
/gate/rackinf/placement/setTranslation 0. -101. 0. mm
/gate/rackinf/vis/forceWireframe              
/gate/rackinf/vis/setVisible true
/gate/geometry/rebuild
   
#====================
# FIRST LEVEL OF RACK - lapiz
#====================
/gate/world/daughters/name lapiz
/gate/world/daughters/insert cylinder
/gate/lapiz/setMaterial StainlessSteel
/gate/lapiz/placement/setTranslation 80.5 0. 0. mm
/gate/lapiz/vis/setColor gray
/gate/lapiz/geometry/setRmax 5. mm
/gate/lapiz/geometry/setRmin 4.99 mm
/gate/lapiz/geometry/setHeight 202. mm
/gate/lapiz/placement/setRotationAxis 1 0 0
/gate/lapiz/placement/setRotationAngle 90 deg
/gate/lapiz/vis/forceSolid
/gate/geometry/rebuild

#====================
# REPEAT-lapiz se tiene 16 lapices
#====================
/gate/lapiz/repeaters/insert ring
/gate/lapiz/ring/setRepeatNumber 16
/gate/lapiz/ring/setPoint1 0. 1. 0. mm
/gate/lapiz/ring/setPoint2 0. 0. 0. mm
/gate/lapiz/ring/disableAutoRotation
/gate/lapiz/vis/forceSolid
/gate/geometry/rebuild

#====================
#PHYSICS PROCESSES
#====================
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/addProcess RadioactiveDecay
/gate/physics/processList Enabled 
/gate/physics/processList Initialized

#====================
#INITIALIZE
#====================
/gate/run/initialize

#====================
#ADDER
#====================
#Para VGATE 9.1
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid

#Para VGATE9.3
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert adder
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/adder/positionPolicy energyWeightedCentroid

#====================
#READOUT
#====================
#Para VGATE 9.1
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2

#Para VGATE9.3
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert readout
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/readout/setDepth 2

#====================
#ENERGY BLURRING #VGate 9.1
#====================
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.015
/gate/digitizer/Singles/blurring/setEnergyOfReference 1173.228 keV
/gate/digitizer/Singles/blurring/setResolution 0.012
/gate/digitizer/Singles/blurring/setEnergyOfReference 1332.492 keV

#====================
#ENERGY RESOLUTION #VGate 9.3 (Antes ENERGY BLURRING)
#====================
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyResolution
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/fwhm 0.015
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/energyOfReference 1173.228 keV
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/fwhm 0.012
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/energyOfReference 1332.492 keV

#====================
#ENERGY WINDOW #VGATE 9.1
#====================
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 0. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 2000. keV

#====================
#ENERGY FRAMING #VGATE 9.3 (Previously Thresholder and Upholder)
#====================
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyFraming
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMin 0. keV
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMax 2000. keV

#====================
#Actividad total de fuente 07/03/2023=119.20 Ci, como son 16 lapices la actividad por cada lapiz = 7.45 Ci
#====================

#====================
#SOURCE 1 1173.228 keV (4.8e+06 es el limite que me quede antes de killed)(como son dos fuente 1 de diferentes enregías la actividad de 7.45 Ci se divide para dos, siendo 3.725 Ci)
#====================
/gate/source/addSource SourceCo601 gps
/gate/source/SourceCo601/setActivity 3.725 Ci
/gate/source/SourceCo601/setType backtoback

#====================
#POSITION 
#====================
/gate/source/SourceCo601/gps/centre 80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo601/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo601/gps/type Volume
/gate/source/SourceCo601/gps/shape Cylinder
/gate/source/SourceCo601/gps/radius 4.985 mm
/gate/source/SourceCo601/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
#/gate/source/SourceCo601/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo601/gps/mintheta 0. deg
/gate/source/SourceCo601/gps/maxtheta 180. deg
/gate/source/SourceCo601/gps/minphi 0. deg
/gate/source/SourceCo601/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo601/gps/ene/type Mono
/gate/source/SourceCo601/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE 
#====================
/gate/source/SourceCo601/visualize 10000 green 20

#====================
#SOURCE 1 1332.492 keV (4.8e+06 es el limite que me quede antes de killed)
#====================
/gate/source/addSource SourceCo6012 gps
/gate/source/SourceCo6012/setActivity 3.725 Ci
/gate/source/SourceCo6012/setType backtoback

#====================
#POSITION 
#====================
/gate/source/SourceCo6012/gps/centre 80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6012/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6012/gps/type Volume
/gate/source/SourceCo6012/gps/shape Cylinder
/gate/source/SourceCo6012/gps/radius 4.985 mm
/gate/source/SourceCo6012/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6012/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6012/gps/mintheta 0. deg
/gate/source/SourceCo6012/gps/maxtheta 180. deg
/gate/source/SourceCo6012/gps/minphi 0. deg
/gate/source/SourceCo6012/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6012/gps/ene/type Mono
/gate/source/SourceCo6012/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE 
#====================
/gate/source/SourceCo6012/visualize 10000 green 20

#====================
#REPEAT SOURCE 16 TIMES EN CADA LAPIZ
#====================
#====================
#SOURCE 2 1173.228 keV
#====================
/gate/source/addSource SourceCo6021 gps
/gate/source/SourceCo6021/setActivity 3.725 Ci
/gate/source/SourceCo6021/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6021/gps/centre 74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6021/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6021/gps/type Volume
/gate/source/SourceCo6021/gps/shape Cylinder
/gate/source/SourceCo6021/gps/radius 4.985 mm
/gate/source/SourceCo6021/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6021/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6021/gps/mintheta 0. deg
/gate/source/SourceCo6021/gps/maxtheta 180. deg
/gate/source/SourceCo6021/gps/minphi 0. deg
/gate/source/SourceCo6021/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6021/gps/ene/type Mono
/gate/source/SourceCo6021/gps/ene/mono 1173.228 keV
/gate/source/SourceCo6021/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6021/visualize 10000 green 20

#====================
#SOURCE 2 1332.492 keV
#====================
/gate/source/addSource SourceCo6022 gps
/gate/source/SourceCo6022/setActivity 3.725 Ci
/gate/source/SourceCo6022/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6022/gps/centre 74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6022/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6022/gps/type Volume
/gate/source/SourceCo6022/gps/shape Cylinder
/gate/source/SourceCo6022/gps/radius 4.985 mm
/gate/source/SourceCo6022/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6022/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6022/gps/mintheta 0. deg
/gate/source/SourceCo6022/gps/maxtheta 180. deg
/gate/source/SourceCo6022/gps/minphi 0. deg
/gate/source/SourceCo6022/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6022/gps/ene/type Mono
/gate/source/SourceCo6022/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6022/visualize 10000 green 20

#====================
#SOURCE 3 1173.228 keV
#====================
/gate/source/addSource SourceCo6031 gps
/gate/source/SourceCo6031/setActivity 3.725 Ci
/gate/source/SourceCo6031/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6031/gps/centre 56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6031/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6031/gps/type Volume
/gate/source/SourceCo6031/gps/shape Cylinder
/gate/source/SourceCo6031/gps/radius 4.985 mm
/gate/source/SourceCo6031/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6031/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6031/gps/mintheta 0. deg
/gate/source/SourceCo6031/gps/maxtheta 180. deg
/gate/source/SourceCo6031/gps/minphi 0. deg
/gate/source/SourceCo6031/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6031/gps/ene/type Mono
/gate/source/SourceCo6031/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6031/visualize 10000 green 20

#====================
#SOURCE 3 1332.492 keV
#====================
/gate/source/addSource SourceCo6032 gps
/gate/source/SourceCo6032/setActivity 3.725 Ci
/gate/source/SourceCo6032/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6032/gps/centre 56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6032/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6032/gps/type Volume
/gate/source/SourceCo6032/gps/shape Cylinder
/gate/source/SourceCo6032/gps/radius 4.985 mm
/gate/source/SourceCo6032/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6032/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6032/gps/mintheta 0. deg
/gate/source/SourceCo6032/gps/maxtheta 180. deg
/gate/source/SourceCo6032/gps/minphi 0. deg
/gate/source/SourceCo6032/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6032/gps/ene/type Mono
/gate/source/SourceCo6032/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6032/visualize 10000 green 20

#====================
#SOURCE 4 1173.228 keV
#====================
/gate/source/addSource SourceCo6041 gps
/gate/source/SourceCo6041/setActivity 3.725 Ci
/gate/source/SourceCo6041/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6041/gps/centre 30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6041/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6041/gps/type Volume
/gate/source/SourceCo6041/gps/shape Cylinder
/gate/source/SourceCo6041/gps/radius 4.985 mm
/gate/source/SourceCo6041/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6041/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6041/gps/mintheta 0. deg
/gate/source/SourceCo6041/gps/maxtheta 180. deg
/gate/source/SourceCo6041/gps/minphi 0. deg
/gate/source/SourceCo6041/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6041/gps/ene/type Mono
/gate/source/SourceCo6041/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6041/visualize 10000 green 20

#====================
#SOURCE 4 1332.492 keV
#====================
/gate/source/addSource SourceCo6042 gps
/gate/source/SourceCo6042/setActivity 3.725 Ci
/gate/source/SourceCo6042/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6042/gps/centre 30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6042/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6042/gps/type Volume
/gate/source/SourceCo6042/gps/shape Cylinder
/gate/source/SourceCo6042/gps/radius 4.985 mm
/gate/source/SourceCo6042/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6042/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6042/gps/mintheta 0. deg
/gate/source/SourceCo6042/gps/maxtheta 180. deg
/gate/source/SourceCo6042/gps/minphi 0. deg
/gate/source/SourceCo6042/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6042/gps/ene/type Mono
/gate/source/SourceCo6042/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6042/visualize 10000 green 20

#====================
#SOURCE 5 1173.228 keV
#====================
/gate/source/addSource SourceCo6051 gps
/gate/source/SourceCo6051/setActivity 3.725 Ci
/gate/source/SourceCo6051/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6051/gps/centre 0. 0. 80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6051/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6051/gps/type Volume
/gate/source/SourceCo6051/gps/shape Cylinder
/gate/source/SourceCo6051/gps/radius 4.985 mm
/gate/source/SourceCo6051/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6051/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6051/gps/mintheta 0. deg
/gate/source/SourceCo6051/gps/maxtheta 180. deg
/gate/source/SourceCo6051/gps/minphi 0. deg
/gate/source/SourceCo6051/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6051/gps/ene/type Mono
/gate/source/SourceCo6051/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6051/visualize 10000 green 20

#====================
#SOURCE 5 1332.492 keV
#====================
/gate/source/addSource SourceCo6052 gps
/gate/source/SourceCo6052/setActivity 3.725 Ci
/gate/source/SourceCo6052/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6052/gps/centre 0. 0. 80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6052/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6052/gps/type Volume
/gate/source/SourceCo6052/gps/shape Cylinder
/gate/source/SourceCo6052/gps/radius 4.985 mm
/gate/source/SourceCo6052/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6052/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6052/gps/mintheta 0. deg
/gate/source/SourceCo6052/gps/maxtheta 180. deg
/gate/source/SourceCo6052/gps/minphi 0. deg
/gate/source/SourceCo6052/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6052/gps/ene/type Mono
/gate/source/SourceCo6052/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6052/visualize 10000 green 20

#====================
#SOURCE 6 1173.228 keV
#====================
/gate/source/addSource SourceCo6061 gps
/gate/source/SourceCo6061/setActivity 3.725 Ci
/gate/source/SourceCo6061/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6061/gps/centre -30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6061/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6061/gps/type Volume
/gate/source/SourceCo6061/gps/shape Cylinder
/gate/source/SourceCo6061/gps/radius 4.985 mm
/gate/source/SourceCo6061/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6061/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6061/gps/mintheta 0. deg
/gate/source/SourceCo6061/gps/maxtheta 180. deg
/gate/source/SourceCo6061/gps/minphi 0. deg
/gate/source/SourceCo6061/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6061/gps/ene/type Mono
/gate/source/SourceCo6061/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6061/visualize 10000 green 20

#====================
#SOURCE 6 1332.492 keV
#====================
/gate/source/addSource SourceCo6062 gps
/gate/source/SourceCo6062/setActivity 3.725 Ci
/gate/source/SourceCo6062/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6062/gps/centre -30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6062/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6062/gps/type Volume
/gate/source/SourceCo6062/gps/shape Cylinder
/gate/source/SourceCo6062/gps/radius 4.985 mm
/gate/source/SourceCo6062/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6062/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6062/gps/mintheta 0. deg
/gate/source/SourceCo6062/gps/maxtheta 180. deg
/gate/source/SourceCo6062/gps/minphi 0. deg
/gate/source/SourceCo6062/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6062/gps/ene/type Mono
/gate/source/SourceCo6062/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6062/visualize 10000 green 20

#====================
#SOURCE 7 1173.228 keV
#====================
/gate/source/addSource SourceCo6071 gps
/gate/source/SourceCo6071/setActivity 3.725 Ci
/gate/source/SourceCo6071/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6071/gps/centre -56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6071/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6071/gps/type Volume
/gate/source/SourceCo6071/gps/shape Cylinder
/gate/source/SourceCo6071/gps/radius 4.985 mm
/gate/source/SourceCo6071/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6071/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6071/gps/mintheta 0. deg
/gate/source/SourceCo6071/gps/maxtheta 180. deg
/gate/source/SourceCo6071/gps/minphi 0. deg
/gate/source/SourceCo6071/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6071/gps/ene/type Mono
/gate/source/SourceCo6071/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6071/visualize 10000 green 20

#====================
#SOURCE 7 1332.492 keV
#====================
/gate/source/addSource SourceCo6072 gps
/gate/source/SourceCo6072/setActivity 3.725 Ci
/gate/source/SourceCo6072/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6072/gps/centre -56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6072/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6072/gps/type Volume
/gate/source/SourceCo6072/gps/shape Cylinder
/gate/source/SourceCo6072/gps/radius 4.985 mm
/gate/source/SourceCo6072/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6072/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6072/gps/mintheta 0. deg
/gate/source/SourceCo6072/gps/maxtheta 180. deg
/gate/source/SourceCo6072/gps/minphi 0. deg
/gate/source/SourceCo6072/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6072/gps/ene/type Mono
/gate/source/SourceCo6072/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6072/visualize 10000 green 20

#====================
#SOURCE 8 1173.228 keV
#====================
/gate/source/addSource SourceCo6081 gps
/gate/source/SourceCo6081/setActivity 3.725 Ci
/gate/source/SourceCo6081/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6081/gps/centre -74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6081/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6081/gps/type Volume
/gate/source/SourceCo6081/gps/shape Cylinder
/gate/source/SourceCo6081/gps/radius 4.985 mm
/gate/source/SourceCo6081/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6081/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6081/gps/mintheta 0. deg
/gate/source/SourceCo6081/gps/maxtheta 180. deg
/gate/source/SourceCo6081/gps/minphi 0. deg
/gate/source/SourceCo6081/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6081/gps/ene/type Mono
/gate/source/SourceCo6081/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6081/visualize 10000 green 20

#====================
#SOURCE 8 1332.492 keV
#====================
/gate/source/addSource SourceCo6082 gps
/gate/source/SourceCo6082/setActivity 3.725 Ci
/gate/source/SourceCo6082/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6082/gps/centre -74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6082/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6082/gps/type Volume
/gate/source/SourceCo6082/gps/shape Cylinder
/gate/source/SourceCo6082/gps/radius 4.985 mm
/gate/source/SourceCo6082/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6082/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6082/gps/mintheta 0. deg
/gate/source/SourceCo6082/gps/maxtheta 180. deg
/gate/source/SourceCo6082/gps/minphi 0. deg
/gate/source/SourceCo6082/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6082/gps/ene/type Mono
/gate/source/SourceCo6082/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6082/visualize 10000 green 20

#====================
#SOURCE 9 1173.228 keV
#====================
/gate/source/addSource SourceCo6091 gps
/gate/source/SourceCo6091/setActivity 3.725 Ci
/gate/source/SourceCo6091/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6091/gps/centre -80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6091/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6091/gps/type Volume
/gate/source/SourceCo6091/gps/shape Cylinder
/gate/source/SourceCo6091/gps/radius 4.985 mm
/gate/source/SourceCo6091/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6091/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6091/gps/mintheta 0. deg
/gate/source/SourceCo6091/gps/maxtheta 180. deg
/gate/source/SourceCo6091/gps/minphi 0. deg
/gate/source/SourceCo6091/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6091/gps/ene/type Mono
/gate/source/SourceCo6091/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6091/visualize 10000 green 20

#====================
#SOURCE 9 1332.492 keV
#====================
/gate/source/addSource SourceCo6092 gps
/gate/source/SourceCo6092/setActivity 3.725 Ci
/gate/source/SourceCo6092/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6092/gps/centre -80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6092/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6092/gps/type Volume
/gate/source/SourceCo6092/gps/shape Cylinder
/gate/source/SourceCo6092/gps/radius 4.985 mm
/gate/source/SourceCo6092/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6092/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6092/gps/mintheta 0. deg
/gate/source/SourceCo6092/gps/maxtheta 180. deg
/gate/source/SourceCo6092/gps/minphi 0. deg
/gate/source/SourceCo6092/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6092/gps/ene/type Mono
/gate/source/SourceCo6092/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6092/visualize 10000 green 20

#====================
#SOURCE 10 1173.228 keV
#====================
/gate/source/addSource SourceCo60101 gps
/gate/source/SourceCo60101/setActivity 3.725 Ci
/gate/source/SourceCo60101/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60101/gps/centre -74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60101/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60101/gps/type Volume
/gate/source/SourceCo60101/gps/shape Cylinder
/gate/source/SourceCo60101/gps/radius 4.985 mm
/gate/source/SourceCo60101/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60101/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60101/gps/mintheta 0. deg
/gate/source/SourceCo60101/gps/maxtheta 180. deg
/gate/source/SourceCo60101/gps/minphi 0. deg
/gate/source/SourceCo60101/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60101/gps/ene/type Mono
/gate/source/SourceCo60101/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60101/visualize 10000 green 20

#====================
#SOURCE 10 1332.492 keV
#====================
/gate/source/addSource SourceCo60102 gps
/gate/source/SourceCo60102/setActivity 3.725 Ci
/gate/source/SourceCo60102/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60102/gps/centre -74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60102/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60102/gps/type Volume
/gate/source/SourceCo60102/gps/shape Cylinder
/gate/source/SourceCo60102/gps/radius 4.985 mm
/gate/source/SourceCo60102/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60102/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60102/gps/mintheta 0. deg
/gate/source/SourceCo60102/gps/maxtheta 180. deg
/gate/source/SourceCo60102/gps/minphi 0. deg
/gate/source/SourceCo60102/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60102/gps/ene/type Mono
/gate/source/SourceCo60102/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60102/visualize 10000 green 20

#====================
#SOURCE 11 1173.228 keV
#====================
/gate/source/addSource SourceCo60111 gps
/gate/source/SourceCo60111/setActivity 3.725 Ci
/gate/source/SourceCo60111/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60111/gps/centre -56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60111/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60111/gps/type Volume
/gate/source/SourceCo60111/gps/shape Cylinder
/gate/source/SourceCo60111/gps/radius 4.985 mm
/gate/source/SourceCo60111/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60111/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60111/gps/mintheta 0. deg
/gate/source/SourceCo60111/gps/maxtheta 180. deg
/gate/source/SourceCo60111/gps/minphi 0. deg
/gate/source/SourceCo60111/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60111/gps/ene/type Mono
/gate/source/SourceCo60111/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60111/visualize 10000 green 20

#====================
#SOURCE 11 1332.492 keV
#====================
/gate/source/addSource SourceCo60112 gps
/gate/source/SourceCo60112/setActivity 3.725 Ci
/gate/source/SourceCo60112/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60112/gps/centre -56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60112/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60112/gps/type Volume
/gate/source/SourceCo60112/gps/shape Cylinder
/gate/source/SourceCo60112/gps/radius 4.985 mm
/gate/source/SourceCo60112/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60112/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60112/gps/mintheta 0. deg
/gate/source/SourceCo60112/gps/maxtheta 180. deg
/gate/source/SourceCo60112/gps/minphi 0. deg
/gate/source/SourceCo60112/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60112/gps/ene/type Mono
/gate/source/SourceCo60112/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60112/visualize 10000 green 20

#====================
#SOURCE 12 1173.228 keV
#====================
/gate/source/addSource SourceCo60121 gps
/gate/source/SourceCo60121/setActivity 3.725 Ci
/gate/source/SourceCo60121/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60121/gps/centre -30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60121/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60121/gps/type Volume
/gate/source/SourceCo60121/gps/shape Cylinder
/gate/source/SourceCo60121/gps/radius 4.985 mm
/gate/source/SourceCo60121/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60121/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60121/gps/mintheta 0. deg
/gate/source/SourceCo60121/gps/maxtheta 180. deg
/gate/source/SourceCo60121/gps/minphi 0. deg
/gate/source/SourceCo60121/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60121/gps/ene/type Mono
/gate/source/SourceCo60121/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60121/visualize 10000 green 20

#====================
#SOURCE 12 1332.492 keV
#====================
/gate/source/addSource SourceCo60122 gps
/gate/source/SourceCo60122/setActivity 3.725 Ci
/gate/source/SourceCo60122/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60122/gps/centre -30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60122/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60122/gps/type Volume
/gate/source/SourceCo60122/gps/shape Cylinder
/gate/source/SourceCo60122/gps/radius 4.985 mm
/gate/source/SourceCo60122/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60122/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60122/gps/mintheta 0. deg
/gate/source/SourceCo60122/gps/maxtheta 180. deg
/gate/source/SourceCo60122/gps/minphi 0. deg
/gate/source/SourceCo60122/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60122/gps/ene/type Mono
/gate/source/SourceCo60122/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60122/visualize 10000 green 20

#====================
#SOURCE 13 1173.228 keV
#====================
/gate/source/addSource SourceCo60131 gps
/gate/source/SourceCo60131/setActivity 3.725 Ci
/gate/source/SourceCo60131/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60131/gps/centre 0. 0. -80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60131/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60131/gps/type Volume
/gate/source/SourceCo60131/gps/shape Cylinder
/gate/source/SourceCo60131/gps/radius 4.985 mm
/gate/source/SourceCo60131/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60131/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60131/gps/mintheta 0. deg
/gate/source/SourceCo60131/gps/maxtheta 180. deg
/gate/source/SourceCo60131/gps/minphi 0. deg
/gate/source/SourceCo60131/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60131/gps/ene/type Mono
/gate/source/SourceCo60131/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60131/visualize 10000 green 20

#====================
#SOURCE 13 1332.492 keV
#====================
/gate/source/addSource SourceCo60132 gps
/gate/source/SourceCo60132/setActivity 3.725 Ci
/gate/source/SourceCo60132/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60132/gps/centre 0. 0. -80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60132/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60132/gps/type Volume
/gate/source/SourceCo60132/gps/shape Cylinder
/gate/source/SourceCo60132/gps/radius 4.985 mm
/gate/source/SourceCo60132/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60132/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60132/gps/mintheta 0. deg
/gate/source/SourceCo60132/gps/maxtheta 180. deg
/gate/source/SourceCo60132/gps/minphi 0. deg
/gate/source/SourceCo60132/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60132/gps/ene/type Mono
/gate/source/SourceCo60132/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60132/visualize 10000 green 20

#====================
#SOURCE 14 1173.228 keV
#====================
/gate/source/addSource SourceCo60141 gps
/gate/source/SourceCo60141/setActivity 3.725 Ci
/gate/source/SourceCo60141/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60141/gps/centre 30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60141/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60141/gps/type Volume
/gate/source/SourceCo60141/gps/shape Cylinder
/gate/source/SourceCo60141/gps/radius 4.985 mm
/gate/source/SourceCo60141/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60141/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60141/gps/mintheta 0. deg
/gate/source/SourceCo60141/gps/maxtheta 180. deg
/gate/source/SourceCo60141/gps/minphi 0. deg
/gate/source/SourceCo60141/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60141/gps/ene/type Mono
/gate/source/SourceCo60141/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60141/visualize 10000 green 20

#====================
#SOURCE 14 1332.492 keV
#====================
/gate/source/addSource SourceCo60142 gps
/gate/source/SourceCo60142/setActivity 3.725 Ci
/gate/source/SourceCo60142/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60142/gps/centre 30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60142/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60142/gps/type Volume
/gate/source/SourceCo60142/gps/shape Cylinder
/gate/source/SourceCo60142/gps/radius 4.985 mm
/gate/source/SourceCo60142/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60142/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60142/gps/mintheta 0. deg
/gate/source/SourceCo60142/gps/maxtheta 180. deg
/gate/source/SourceCo60142/gps/minphi 0. deg
/gate/source/SourceCo60142/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60142/gps/ene/type Mono
/gate/source/SourceCo60142/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60142/visualize 10000 green 20

#====================
#SOURCE 15 1173.228 keV
#====================
/gate/source/addSource SourceCo60151 gps
/gate/source/SourceCo60151/setActivity 3.725 Ci
/gate/source/SourceCo60151/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60151/gps/centre 56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60151/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60151/gps/type Volume
/gate/source/SourceCo60151/gps/shape Cylinder
/gate/source/SourceCo60151/gps/radius 4.985 mm
/gate/source/SourceCo60151/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60151/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60151/gps/mintheta 0. deg
/gate/source/SourceCo60151/gps/maxtheta 180. deg
/gate/source/SourceCo60151/gps/minphi 0. deg
/gate/source/SourceCo60151/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60151/gps/ene/type Mono
/gate/source/SourceCo60151/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60151/visualize 10000 green 20

#====================
#SOURCE 15 1332.492 keV
#====================
/gate/source/addSource SourceCo60152 gps
/gate/source/SourceCo60152/setActivity 3.725 Ci
/gate/source/SourceCo60152/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60152/gps/centre 56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60152/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60152/gps/type Volume
/gate/source/SourceCo60152/gps/shape Cylinder
/gate/source/SourceCo60152/gps/radius 4.985 mm
/gate/source/SourceCo60152/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60152/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60152/gps/mintheta 0. deg
/gate/source/SourceCo60152/gps/maxtheta 180. deg
/gate/source/SourceCo60152/gps/minphi 0. deg
/gate/source/SourceCo60152/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60152/gps/ene/type Mono
/gate/source/SourceCo60152/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60152/visualize 10000 green 20

#====================
#SOURCE 16 1173.228 keV
#====================
/gate/source/addSource SourceCo60161 gps
/gate/source/SourceCo60161/setActivity 3.725 Ci
/gate/source/SourceCo60161/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60161/gps/centre 74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60161/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60161/gps/type Volume
/gate/source/SourceCo60161/gps/shape Cylinder
/gate/source/SourceCo60161/gps/radius 4.985 mm
/gate/source/SourceCo60161/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60161/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60161/gps/mintheta 0. deg
/gate/source/SourceCo60161/gps/maxtheta 180. deg
/gate/source/SourceCo60161/gps/minphi 0. deg
/gate/source/SourceCo60161/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60161/gps/ene/type Mono
/gate/source/SourceCo60161/gps/ene/mono 1173.228 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60161/visualize 10000 green 20

#====================
#SOURCE 16 1332.492 keV
#====================
/gate/source/addSource SourceCo60162 gps
/gate/source/SourceCo60162/setActivity 3.725 Ci
/gate/source/SourceCo60162/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo60162/gps/centre 74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo60162/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo60162/gps/type Volume
/gate/source/SourceCo60162/gps/shape Cylinder
/gate/source/SourceCo60162/gps/radius 4.985 mm
/gate/source/SourceCo60162/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo60162/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo60162/gps/mintheta 0. deg
/gate/source/SourceCo60162/gps/maxtheta 180. deg
/gate/source/SourceCo60162/gps/minphi 0. deg
/gate/source/SourceCo60162/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo60162/gps/ene/type Mono
/gate/source/SourceCo60162/gps/ene/mono 1332.492 keV

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo60162/visualize 10000 green 20

#====================
#ASCII OUTPUT FORMAT
#====================
/gate/output/ascii/enable
/gate/output/ascii/setFileName detector1
/gate/output/ascii/setOutFileHitsFlag 0
/gate/output/ascii/setOutFileSinglesFlag 1

#====================
#ROOT OUTPUT FORMAT
#====================
/gate/output/root/enable
/gate/output/root/setFileName detector1
/gate/output/root/setRootSinglesFlag 1

#====================
#TIME SLICE
#====================
/gate/application/setTimeSlice     10. s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      3600. s

#====================
#SEED 
#====================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed default
/gate/random/verbose 0

#====================
#START ACQUISITION
#====================
/gate/application/startDAQ




