#====================
#VISUALIZATION
#====================
/vis/open OGLIQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 60 30
/vis/viewer/zoom 0
/vis/viewer/set/style surface
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/endOfEventAction accumulate -4

#====================
#====================
#SET MATERIALS
#====================
/gate/geometry/setMaterialDatabase GateMaterials.db

#====================
# WORLD
#====================
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm

#====================
# PORTAMUESTRA (cuerpo del cilindro)
#====================
/gate/world/daughters/name portamuestra
/gate/world/daughters/insert cylinder
/gate/portamuestra/setMaterial Aluminium
/gate/portamuestra/vis/setColor white
/gate/portamuestra/geometry/setRmax 74. mm
/gate/portamuestra/geometry/setRmin 73.75 mm
/gate/portamuestra/geometry/setHeight 199.5 mm
/gate/portamuestra/placement/setRotationAxis 1 0 0
/gate/portamuestra/placement/setRotationAngle 90 deg
/gate/portamuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA PORTAMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapaportamuestra
/gate/world/daughters/insert cylinder
/gate/tapaportamuestra/setMaterial Aluminium
/gate/tapaportamuestra/vis/setColor white
/gate/tapaportamuestra/geometry/setRmax 74. mm
/gate/tapaportamuestra/geometry/setRmin 0. mm
/gate/tapaportamuestra/geometry/setHeight 0.5 mm
/gate/tapaportamuestra/placement/setRotationAxis 1 0 0
/gate/tapaportamuestra/placement/setRotationAngle 90 deg
/gate/tapaportamuestra/placement/setTranslation 0. -99.75 0. mm
/gate/tapaportamuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# CONTENEDOR DE MUESTRA 
#====================
/gate/world/daughters/name contenedormuestra
/gate/world/daughters/insert cylinder
/gate/contenedormuestra/setMaterial PVC
/gate/contenedormuestra/vis/setColor cyan
/gate/contenedormuestra/geometry/setRmax 50.97 mm
/gate/contenedormuestra/geometry/setRmin 50.47 mm
/gate/contenedormuestra/geometry/setHeight 129.5 mm
/gate/contenedormuestra/placement/setRotationAxis 1 0 0
/gate/contenedormuestra/placement/setRotationAngle 90 deg
/gate/contenedormuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapacontenedorsup
/gate/world/daughters/insert cylinder
/gate/tapacontenedorsup/setMaterial PVC
/gate/tapacontenedorsup/vis/setColor cyan
/gate/tapacontenedorsup/geometry/setRmax 62.63 mm
/gate/tapacontenedorsup/geometry/setRmin 61.63 mm
/gate/tapacontenedorsup/geometry/setHeight 20.8 mm
/gate/tapacontenedorsup/placement/setRotationAxis 1 0 0
/gate/tapacontenedorsup/placement/setRotationAngle 90 deg
/gate/tapacontenedorsup/placement/setTranslation 0. 75.15 0. mm
/gate/tapacontenedorsup/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA PARA LA TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapasup
/gate/world/daughters/insert cylinder
/gate/tapasup/setMaterial PVC
/gate/tapasup/vis/setColor cyan
/gate/tapasup/geometry/setRmax 62.63 mm
/gate/tapasup/geometry/setRmin 0. mm
/gate/tapasup/geometry/setHeight 0.2 mm
/gate/tapasup/placement/setRotationAxis 1 0 0
/gate/tapasup/placement/setRotationAngle 90 deg
/gate/tapasup/placement/setTranslation 0. 64.76 0. mm
/gate/tapasup/vis/forceWireframe
/gate/geometry/rebuild

#====================
# TAPA CONTENEDORMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapacontenedormuestra
/gate/world/daughters/insert cylinder
/gate/tapacontenedormuestra/setMaterial PVC
/gate/tapacontenedormuestra/vis/setColor cyan
/gate/tapacontenedormuestra/geometry/setRmax 50.97 mm
/gate/tapacontenedormuestra/geometry/setRmin 0. mm
/gate/tapacontenedormuestra/geometry/setHeight 0.5 mm
/gate/tapacontenedormuestra/placement/setRotationAxis 1 0 0
/gate/tapacontenedormuestra/placement/setRotationAngle 90 deg
/gate/tapacontenedormuestra/placement/setTranslation 0. -64.75 0. mm
/gate/tapacontenedormuestra/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE TUBOS (con agujeros) 
#====================
/gate/world/daughters/name soportetubos
/gate/world/daughters/insert cylinder
/gate/soportetubos/setMaterial Polypropilene
/gate/soportetubos/vis/setColor red
/gate/soportetubos/geometry/setRmax 50.965 mm
/gate/soportetubos/geometry/setRmin 0. mm
/gate/soportetubos/geometry/setHeight 25. mm
/gate/soportetubos/placement/setRotationAxis 1 0 0
/gate/soportetubos/placement/setRotationAngle 90 deg
/gate/soportetubos/placement/setTranslation 0. -12.5 0. mm
/gate/soportetubos/vis/forceWireframe
/gate/geometry/rebuild

#====================
#GEOMETRY-CIRCULO MEDIO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulomedio
/gate/world/daughters/insert cylinder
/gate/circulomedio/setMaterial Polypropilene  
/gate/circulomedio/vis/setColor red           
/gate/circulomedio/geometry/setRmax 8.6 mm
/gate/circulomedio/geometry/setRmin 8.55 mm
/gate/circulomedio/geometry/setHeight 25. mm
/gate/circulomedio/placement/setRotationAxis 1 0 0
/gate/circulomedio/placement/setRotationAngle 90 deg
/gate/circulomedio/placement/setTranslation 0. -12.5 0. mm
/gate/circulomedio/vis/forceWireframe              
/gate/circulomedio/vis/setVisible true
/gate/geometry/rebuild 

#====================
#GEOMETRY-CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circuloexterno
/gate/world/daughters/insert cylinder
/gate/circuloexterno/setMaterial Polypropilene  
/gate/circuloexterno/vis/setColor red           
/gate/circuloexterno/geometry/setRmax 8.6 mm
/gate/circuloexterno/geometry/setRmin 8.55 mm
/gate/circuloexterno/geometry/setHeight 25. mm
/gate/circuloexterno/placement/setRotationAxis 1 0 0
/gate/circuloexterno/placement/setRotationAngle 90 deg
/gate/circuloexterno/placement/setTranslation 39. -12.5 0. mm
/gate/circuloexterno/vis/forceWireframe              
/gate/circuloexterno/vis/setVisible true
/gate/geometry/rebuild

#====================
# REPEAT-CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circuloexterno/repeaters/insert ring
/gate/circuloexterno/ring/setRepeatNumber 12
/gate/circuloexterno/ring/setPoint1 0. 1. 0. mm
/gate/circuloexterno/ring/setPoint2 0. 0. 0. mm
/gate/circuloexterno/ring/disableAutoRotation
/gate/circuloexterno/vis/forceWireframe
/gate/geometry/rebuild

#====================
#GEOMETRY-CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulointerno
/gate/world/daughters/insert cylinder
/gate/circulointerno/setMaterial Polypropilene  
/gate/circulointerno/vis/setColor red           
/gate/circulointerno/geometry/setRmax 8.6 mm
/gate/circulointerno/geometry/setRmin 8.55 mm
/gate/circulointerno/geometry/setHeight 25. mm
/gate/circulointerno/placement/setRotationAxis 1 0 0
/gate/circulointerno/placement/setRotationAngle 90 deg
/gate/circulointerno/placement/setTranslation 18.5 -12.5 11. mm
/gate/circulointerno/vis/forceWireframe              
/gate/geometry/rebuild

#====================
# REPEAT-CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circulointerno/repeaters/insert ring
/gate/circulointerno/ring/setRepeatNumber 6
/gate/circulointerno/ring/setPoint1 0. 1. 0. mm
/gate/circulointerno/ring/setPoint2 0. 0. 0. mm
/gate/circulointerno/ring/disableAutoRotation
/gate/circulointerno/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 1
#====================
/gate/world/daughters/name soportemadera1
/gate/world/daughters/insert cylinder
/gate/soportemadera1/setMaterial Wood
/gate/soportemadera1/vis/setColor yellow
/gate/soportemadera1/geometry/setRmax 55.5 mm
/gate/soportemadera1/geometry/setRmin 0. mm
/gate/soportemadera1/geometry/setHeight 9. mm
/gate/soportemadera1/placement/setRotationAxis 1 0 0
/gate/soportemadera1/placement/setRotationAngle 90 deg
/gate/soportemadera1/placement/setTranslation 0. -69.25 0. mm
/gate/soportemadera1/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 2
#====================
/gate/world/daughters/name soportemadera2
/gate/world/daughters/insert box
/gate/soportemadera2/setMaterial Wood
/gate/soportemadera2/vis/setColor yellow
/gate/soportemadera2/geometry/setXLength 30. mm
/gate/soportemadera2/geometry/setYLength 30. mm
/gate/soportemadera2/geometry/setZLength 15. mm
/gate/soportemadera2/placement/setRotationAxis 1 0 0
/gate/soportemadera2/placement/setRotationAngle 90 deg
/gate/soportemadera2/placement/setTranslation 0. -81.5 0. mm
/gate/soportemadera2/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SOPORTE DE MADERA PARA CONTENEDOR DE MUESTRA 3
#====================
/gate/world/daughters/name soportemadera3
/gate/world/daughters/insert cylinder
/gate/soportemadera3/setMaterial Wood
/gate/soportemadera3/vis/setColor yellow
/gate/soportemadera3/geometry/setRmax 55.5 mm
/gate/soportemadera3/geometry/setRmin 0. mm
/gate/soportemadera3/geometry/setHeight 9. mm
/gate/soportemadera3/placement/setRotationAxis 1 0 0
/gate/soportemadera3/placement/setRotationAngle 90 deg
/gate/soportemadera3/placement/setTranslation 0. -93.45 0. mm
/gate/soportemadera3/vis/forceWireframe
/gate/geometry/rebuild

#====================
#TAPA- tapa del tubo Fricke
#====================
/gate/world/daughters/name tapa
/gate/world/daughters/insert cylinder
/gate/tapa/setMaterial Polypropilene
/gate/tapa/vis/setColor white
/gate/tapa/placement/setTranslation 0. 51. 0. mm
/gate/tapa/geometry/setRmax 8.5 mm
/gate/tapa/geometry/setRmin 0. mm
/gate/tapa/geometry/setHeight 15. mm
/gate/tapa/placement/setRotationAxis 1 0 0
/gate/tapa/placement/setRotationAngle 90 deg
/gate/tapa/vis/forceWireframe
/gate/geometry/rebuild

#====================
# SYSTEM - scanner
#====================
/gate/world/daughters/name scanner
/gate/world/daughters/insert cylinder
/gate/scanner/setMaterial Air
/gate/scanner/vis/setColor yellow
/gate/scanner/geometry/setRmax 9. mm
/gate/scanner/geometry/setRmin 0. mm
/gate/scanner/geometry/setHeight 87. mm
/gate/scanner/placement/setRotationAxis 1 0 0
/gate/scanner/placement/setRotationAngle 90 deg
/gate/scanner/vis/forceWireframe
/gate/geometry/rebuild

#====================
#FIRST LEVEL OF THE SYSTEM-tubo Fricke
#====================
/gate/scanner/daughters/name tubo
/gate/scanner/daughters/insert cylinder
/gate/tubo/setMaterial Glass
/gate/tubo/vis/setColor gray
/gate/tubo/geometry/setRmax 8.5 mm
/gate/tubo/geometry/setRmin 8.495 mm
/gate/tubo/geometry/setHeight 86. mm
/gate/tubo/vis/forceWireframe
/gate/geometry/rebuild

#====================
#SECOND LEVEL OF THE SYSTEM-aguatubo Fricke
#====================
/gate/tubo/daughters/name aguafricke
/gate/tubo/daughters/insert cylinder
/gate/aguafricke/setMaterial Water
/gate/aguafricke/vis/setColor blue
/gate/aguafricke/geometry/setRmax 8.49 mm
/gate/aguafricke/geometry/setRmin 0. mm
/gate/aguafricke/geometry/setHeight 85.9 mm
/gate/aguafricke/vis/forceWireframe
/gate/geometry/rebuild

#====================
#ATTACH VOLUMES TO A SYSTEM
#====================
/gate/systems/scanner/level1/attach tubo
/gate/systems/scanner/level2/attach aguafricke

#====================
#DEFINE A SENSITIVE DETECTOR
#====================
/gate/aguafricke/attachCrystalSD
/gate/systems/scanner/describe

#====================
#GEOMETRY-Parte superior RACK (sin agujeros)
#====================
/gate/world/daughters/name racksup
/gate/world/daughters/insert cylinder
/gate/racksup/setMaterial StainlessSteel  
/gate/racksup/vis/setColor gray           
/gate/racksup/geometry/setRmax 85.5 mm
/gate/racksup/geometry/setRmin 75.5 mm
/gate/racksup/geometry/setHeight 1. mm
/gate/racksup/placement/setRotationAxis 1 0 0
/gate/racksup/placement/setRotationAngle 90 deg
/gate/racksup/placement/setTranslation 0. 101. 0. mm
/gate/racksup/vis/forceWireframe              
/gate/racksup/vis/setVisible true
/gate/geometry/rebuild 

#====================
#GEOMETRY-Parte inferior RACK (sin agujeros)
#====================
/gate/world/daughters/name rackinf
/gate/world/daughters/insert cylinder
/gate/rackinf/setMaterial StainlessSteel  
/gate/rackinf/vis/setColor gray           
/gate/rackinf/geometry/setRmax 85.5 mm
/gate/rackinf/geometry/setRmin 75.5 mm
/gate/rackinf/geometry/setHeight 1. mm
/gate/rackinf/placement/setRotationAxis 1 0 0
/gate/rackinf/placement/setRotationAngle 90 deg
/gate/rackinf/placement/setTranslation 0. -101. 0. mm
/gate/rackinf/vis/forceWireframe              
/gate/rackinf/vis/setVisible true
/gate/geometry/rebuild
   
#====================
# FIRST LEVEL OF RACK - lapiz
#====================
/gate/world/daughters/name lapiz
/gate/world/daughters/insert cylinder
/gate/lapiz/setMaterial StainlessSteel
/gate/lapiz/placement/setTranslation 80.5 0. 0. mm
/gate/lapiz/vis/setColor gray
/gate/lapiz/geometry/setRmax 5. mm
/gate/lapiz/geometry/setRmin 4.99 mm
/gate/lapiz/geometry/setHeight 202. mm
/gate/lapiz/placement/setRotationAxis 1 0 0
/gate/lapiz/placement/setRotationAngle 90 deg
/gate/lapiz/vis/forceSolid
/gate/geometry/rebuild

#====================
# REPEAT-lapiz se tiene 16 lapices
#====================
/gate/lapiz/repeaters/insert ring
/gate/lapiz/ring/setRepeatNumber 16
/gate/lapiz/ring/setPoint1 0. 1. 0. mm
/gate/lapiz/ring/setPoint2 0. 0. 0. mm
/gate/lapiz/ring/disableAutoRotation
/gate/lapiz/vis/forceSolid
/gate/geometry/rebuild

#====================
#PHYSICS PROCESSES
#====================
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled 
/gate/physics/processList Initialized

#====================
#INITIALIZE
#====================
/gate/run/initialize

#====================
#ADDER
#====================
#Para VGATE 9.1
#/gate/digitizer/Singles/insert adder

#Para VGATE9.3
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert adder

#====================
#READOUT
#====================
#Para VGATE 9.1
#/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setDepth 1

#Para VGATE9.3
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/readout/setDepth 1


#====================
#ENERGY BLURRING #VGate 9.1
#====================
#/gate/digitizer/Singles/insert blurring
#/gate/digitizer/Singles/blurring/setResolution 0.001
#/gate/digitizer/Singles/blurring/setEnergyOfReference 1173.228 keV
#/gate/digitizer/Singles/blurring/setEnergyOfReference 1332.492 keV

#====================
#ENERGY RESOLUTION #VGate 9.3 (Antes ENERGY BLURRING)
#====================
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/fwhm 0.001
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/energyOfReference 1173.228 keV
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/energyOfReference 1332.492 keV

#====================
#ENERGY WINDOW #VGATE 9.1
#====================
#/gate/digitizer/Singles/insert thresholder
#/gate/digitizer/Singles/thresholder/setThreshold 0. keV
#/gate/digitizer/Singles/insert upholder
#/gate/digitizer/Singles/upholder/setUphold 2000. keV

#====================
#ENERGY FRAMING #VGATE 9.3 (Previously Thresholder and Upholder)
#====================
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMin 0. keV
/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMax 2000. keV

#====================
#Actividades totales de fuente 07/03/2023=119.2 Ci, para 10/04/2023=117.788 Ci y para 12/04/2023=117.704 Ci, obteniendo un valor promedio de actividad de 118.23 Ci, como son 16 lapices la actividad por cada lapiz = 7.38837634 Ci
#====================

#====================
#SOURCE 1 (4.8e+06 es el limite que me quede antes de killed)
#====================
/gate/source/addSource SourceCo601 gps
/gate/source/SourceCo601/setActivity 7.38837634 Ci
/gate/source/SourceCo601/setType backtoback

#====================
#POSITION 
#====================
/gate/source/SourceCo601/gps/centre 80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo601/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo601/gps/type Volume
/gate/source/SourceCo601/gps/shape Cylinder
/gate/source/SourceCo601/gps/radius 4.985 mm
/gate/source/SourceCo601/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo601/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo601/gps/mintheta 0. deg
/gate/source/SourceCo601/gps/maxtheta 180. deg
/gate/source/SourceCo601/gps/minphi 0. deg
/gate/source/SourceCo601/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo601/gps/ene/type UserSpectrum
/gate/source/SourceCo601/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE 
#====================
/gate/source/SourceCo601/visualize 10000 green 20


#====================
#REPEAT SOURCE 16 TIMES EN CADA LAPIZ
#====================
#====================
#SOURCE 2 
#====================
/gate/source/addSource SourceCo602 gps
/gate/source/SourceCo602/setActivity 7.38837634 Ci
/gate/source/SourceCo602/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo602/gps/centre 74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo602/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo602/gps/type Volume
/gate/source/SourceCo602/gps/shape Cylinder
/gate/source/SourceCo602/gps/radius 4.985 mm
/gate/source/SourceCo602/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo602/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo602/gps/mintheta 0. deg
/gate/source/SourceCo602/gps/maxtheta 180. deg
/gate/source/SourceCo602/gps/minphi 0. deg
/gate/source/SourceCo602/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo602/gps/ene/type UserSpectrum
/gate/source/SourceCo602/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo602/visualize 10000 green 20


#====================
#SOURCE 3 
#====================
/gate/source/addSource SourceCo603 gps
/gate/source/SourceCo603/setActivity 7.38837634 Ci
/gate/source/SourceCo603/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo603/gps/centre 56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo603/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo603/gps/type Volume
/gate/source/SourceCo603/gps/shape Cylinder
/gate/source/SourceCo603/gps/radius 4.985 mm
/gate/source/SourceCo603/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo603/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo603/gps/mintheta 0. deg
/gate/source/SourceCo603/gps/maxtheta 180. deg
/gate/source/SourceCo603/gps/minphi 0. deg
/gate/source/SourceCo603/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo603/gps/ene/type UserSpectrum
/gate/source/SourceCo603/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo603/visualize 10000 green 20

#====================
#SOURCE 4 
#====================
/gate/source/addSource SourceCo604 gps
/gate/source/SourceCo604/setActivity 7.38837634 Ci
/gate/source/SourceCo604/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo604/gps/centre 30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo604/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo604/gps/type Volume
/gate/source/SourceCo604/gps/shape Cylinder
/gate/source/SourceCo604/gps/radius 4.985 mm
/gate/source/SourceCo604/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo604/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo604/gps/mintheta 0. deg
/gate/source/SourceCo604/gps/maxtheta 180. deg
/gate/source/SourceCo604/gps/minphi 0. deg
/gate/source/SourceCo604/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo604/gps/ene/type UserSpectrum
/gate/source/SourceCo604/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo604/visualize 10000 green 20


#====================
#SOURCE 5 
#====================
/gate/source/addSource SourceCo605 gps
/gate/source/SourceCo605/setActivity 7.38837634 Ci
/gate/source/SourceCo605/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo605/gps/centre 0. 0. 80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo605/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo605/gps/type Volume
/gate/source/SourceCo605/gps/shape Cylinder
/gate/source/SourceCo605/gps/radius 4.985 mm
/gate/source/SourceCo605/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo605/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo605/gps/mintheta 0. deg
/gate/source/SourceCo605/gps/maxtheta 180. deg
/gate/source/SourceCo605/gps/minphi 0. deg
/gate/source/SourceCo605/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo605/gps/ene/type UserSpectrum
/gate/source/SourceCo605/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo605/visualize 10000 green 20


#====================
#SOURCE 6 
#====================
/gate/source/addSource SourceCo606 gps
/gate/source/SourceCo606/setActivity 7.38837634 Ci
/gate/source/SourceCo606/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo606/gps/centre -30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo606/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo606/gps/type Volume
/gate/source/SourceCo606/gps/shape Cylinder
/gate/source/SourceCo606/gps/radius 4.985 mm
/gate/source/SourceCo606/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo606/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo606/gps/mintheta 0. deg
/gate/source/SourceCo606/gps/maxtheta 180. deg
/gate/source/SourceCo606/gps/minphi 0. deg
/gate/source/SourceCo606/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo606/gps/ene/type UserSpectrum
/gate/source/SourceCo606/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo606/visualize 10000 green 20


#====================
#SOURCE 7
#====================
/gate/source/addSource SourceCo607 gps
/gate/source/SourceCo607/setActivity 7.38837634 Ci
/gate/source/SourceCo607/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo607/gps/centre -56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo607/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo607/gps/type Volume
/gate/source/SourceCo607/gps/shape Cylinder
/gate/source/SourceCo607/gps/radius 4.985 mm
/gate/source/SourceCo607/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo607/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo607/gps/mintheta 0. deg
/gate/source/SourceCo607/gps/maxtheta 180. deg
/gate/source/SourceCo607/gps/minphi 0. deg
/gate/source/SourceCo607/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo607/gps/ene/type UserSpectrum
/gate/source/SourceCo607/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo607/visualize 10000 green 20


#====================
#SOURCE 8 1173.228 keV
#====================
/gate/source/addSource SourceCo608 gps
/gate/source/SourceCo608/setActivity 7.38837634 Ci
/gate/source/SourceCo608/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo608/gps/centre -74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo608/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo608/gps/type Volume
/gate/source/SourceCo608/gps/shape Cylinder
/gate/source/SourceCo608/gps/radius 4.985 mm
/gate/source/SourceCo608/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo608/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo608/gps/mintheta 0. deg
/gate/source/SourceCo608/gps/maxtheta 180. deg
/gate/source/SourceCo608/gps/minphi 0. deg
/gate/source/SourceCo608/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo608/gps/ene/type UserSpectrum
/gate/source/SourceCo608/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo608/visualize 10000 green 20


#====================
#SOURCE 9
#====================
/gate/source/addSource SourceCo609 gps
/gate/source/SourceCo609/setActivity 7.38837634 Ci
/gate/source/SourceCo609/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo609/gps/centre -80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo609/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo609/gps/type Volume
/gate/source/SourceCo609/gps/shape Cylinder
/gate/source/SourceCo609/gps/radius 4.985 mm
/gate/source/SourceCo609/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo609/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo609/gps/mintheta 0. deg
/gate/source/SourceCo609/gps/maxtheta 180. deg
/gate/source/SourceCo609/gps/minphi 0. deg
/gate/source/SourceCo609/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo609/gps/ene/type UserSpectrum
/gate/source/SourceCo609/gps/setSpectrumFile SpectrumenergyCo60.txt


#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo609/visualize 10000 green 20


#====================
#SOURCE 10
#====================
/gate/source/addSource SourceCo6010 gps
/gate/source/SourceCo6010/setActivity 7.38837634 Ci
/gate/source/SourceCo6010/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6010/gps/centre -74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6010/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6010/gps/type Volume
/gate/source/SourceCo6010/gps/shape Cylinder
/gate/source/SourceCo6010/gps/radius 4.985 mm
/gate/source/SourceCo6010/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6010/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6010/gps/mintheta 0. deg
/gate/source/SourceCo6010/gps/maxtheta 180. deg
/gate/source/SourceCo6010/gps/minphi 0. deg
/gate/source/SourceCo6010/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6010/gps/ene/type UserSpectrum
/gate/source/SourceCo6010/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6010/visualize 10000 green 20


#====================
#SOURCE 11
#====================
/gate/source/addSource SourceCo6011 gps
/gate/source/SourceCo6011/setActivity 7.38837634 Ci
/gate/source/SourceCo6011/setType backtoback
#====================
#POSITION
#====================
/gate/source/SourceCo6011/gps/centre -56.9 0. -56.9 mm
#====================
#PARTICLE
#====================
/gate/source/SourceCo6011/gps/particle gamma
#====================
#TYPE
#====================
/gate/source/SourceCo6011/gps/type Volume
/gate/source/SourceCo6011/gps/shape Cylinder
/gate/source/SourceCo6011/gps/radius 4.985 mm
/gate/source/SourceCo6011/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6011/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6011/gps/mintheta 0. deg
/gate/source/SourceCo6011/gps/maxtheta 180. deg
/gate/source/SourceCo6011/gps/minphi 0. deg
/gate/source/SourceCo6011/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6011/gps/ene/type UserSpectrum
/gate/source/SourceCo6011/gps/setSpectrumFile SpectrumenergyCo60.txt
#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6011/visualize 10000 green 20


#====================
#SOURCE 12 
#====================
/gate/source/addSource SourceCo6012 gps
/gate/source/SourceCo6012/setActivity 7.38837634 Ci
/gate/source/SourceCo6012/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6012/gps/centre -30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6012/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6012/gps/type Volume
/gate/source/SourceCo6012/gps/shape Cylinder
/gate/source/SourceCo6012/gps/radius 4.985 mm
/gate/source/SourceCo6012/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6012/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6012/gps/mintheta 0. deg
/gate/source/SourceCo6012/gps/maxtheta 180. deg
/gate/source/SourceCo6012/gps/minphi 0. deg
/gate/source/SourceCo6012/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6012/gps/ene/type UserSpectrum
/gate/source/SourceCo6012/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6012/visualize 10000 green 20


#====================
#SOURCE 13
#====================
/gate/source/addSource SourceCo6013 gps
/gate/source/SourceCo6013/setActivity 7.38837634 Ci
/gate/source/SourceCo6013/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6013/gps/centre 0. 0. -80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6013/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6013/gps/type Volume
/gate/source/SourceCo6013/gps/shape Cylinder
/gate/source/SourceCo6013/gps/radius 4.985 mm
/gate/source/SourceCo6013/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6013/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6013/gps/mintheta 0. deg
/gate/source/SourceCo6013/gps/maxtheta 180. deg
/gate/source/SourceCo6013/gps/minphi 0. deg
/gate/source/SourceCo6013/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6013/gps/ene/type UserSpectrum
/gate/source/SourceCo6013/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6013/visualize 10000 green 20


#====================
#SOURCE 14
#====================
/gate/source/addSource SourceCo6014 gps
/gate/source/SourceCo6014/setActivity 7.38837634 Ci
/gate/source/SourceCo6014/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6014/gps/centre 30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6014/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6014/gps/type Volume
/gate/source/SourceCo6014/gps/shape Cylinder
/gate/source/SourceCo6014/gps/radius 4.985 mm
/gate/source/SourceCo6014/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6014/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6014/gps/mintheta 0. deg
/gate/source/SourceCo6014/gps/maxtheta 180. deg
/gate/source/SourceCo6014/gps/minphi 0. deg
/gate/source/SourceCo6014/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6014/gps/ene/type UserSpectrum
/gate/source/SourceCo6014/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6014/visualize 10000 green 20


#====================
#SOURCE 15
#====================
/gate/source/addSource SourceCo6015 gps
/gate/source/SourceCo6015/setActivity 7.38837634 Ci
/gate/source/SourceCo6015/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6015/gps/centre 56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6015/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6015/gps/type Volume
/gate/source/SourceCo6015/gps/shape Cylinder
/gate/source/SourceCo6015/gps/radius 4.985 mm
/gate/source/SourceCo6015/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6015/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6015/gps/mintheta 0. deg
/gate/source/SourceCo6015/gps/maxtheta 180. deg
/gate/source/SourceCo6015/gps/minphi 0. deg
/gate/source/SourceCo6015/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6015/gps/ene/type UserSpectrum
/gate/source/SourceCo6015/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6015/visualize 10000 green 20


#====================
#SOURCE 16
#====================
/gate/source/addSource SourceCo6016 gps
/gate/source/SourceCo6016/setActivity 7.38837634 Ci
/gate/source/SourceCo6016/setType backtoback

#====================
#POSITION
#====================
/gate/source/SourceCo6016/gps/centre 74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6016/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6016/gps/type Volume
/gate/source/SourceCo6016/gps/shape Cylinder
/gate/source/SourceCo6016/gps/radius 4.985 mm
/gate/source/SourceCo6016/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6016/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6016/gps/mintheta 0. deg
/gate/source/SourceCo6016/gps/maxtheta 180. deg
/gate/source/SourceCo6016/gps/minphi 0. deg
/gate/source/SourceCo6016/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6016/gps/ene/type UserSpectrum
/gate/source/SourceCo6016/gps/setSpectrumFile SpectrumenergyCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6016/visualize 10000 green 20


#====================
#ASCII OUTPUT FORMAT
#====================
/gate/output/ascii/enable true
/gate/output/ascii/setFileName testdetector1
/gate/output/ascii/setOutFileHitsFlag 1
/gate/output/ascii/setOutFileSinglesFlag 1

#====================
#ROOT OUTPUT FORMAT
#====================
/gate/output/root/enable true
/gate/output/root/setFileName testdetector1
/gate/output/root/setRootSinglesFlag 1

#====================
#TIME SLICE
#====================
/gate/application/setTimeSlice     10.  s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      60.  s

#====================
#SEED 
#====================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed default
/gate/random/verbose 1

#====================
#START ACQUISITION
#====================
/gate/application/startDAQ



