#====================
#VISUALIZATION
#====================
/vis/open OGLIQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 60 30
/vis/viewer/zoom 3
/vis/viewer/set/style surface
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/endOfEventAction accumulate -4

#====================
#====================
#SET MATERIALS
#====================
/gate/geometry/setMaterialDatabase GateMaterials.db

#====================
# WORLD
#====================
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm

#====================
# PORTAMUESTRA (cuerpo del cilindro)
#====================
/gate/world/daughters/name portamuestra
/gate/world/daughters/insert cylinder
/gate/portamuestra/setMaterial Aluminium
/gate/portamuestra/vis/setColor white
/gate/portamuestra/geometry/setRmax 74. mm
/gate/portamuestra/geometry/setRmin 73.75 mm
/gate/portamuestra/geometry/setHeight 199.5 mm
/gate/portamuestra/placement/setRotationAxis 1 0 0
/gate/portamuestra/placement/setRotationAngle 90 deg
/gate/portamuestra/vis/forceWireframe

#====================
# TAPA PORTAMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapaportamuestra
/gate/world/daughters/insert cylinder
/gate/tapaportamuestra/setMaterial Aluminium
/gate/tapaportamuestra/vis/setColor white
/gate/tapaportamuestra/geometry/setRmax 74. mm
/gate/tapaportamuestra/geometry/setRmin 0. mm
/gate/tapaportamuestra/geometry/setHeight 0.5 mm
/gate/tapaportamuestra/placement/setRotationAxis 1 0 0
/gate/tapaportamuestra/placement/setRotationAngle 90 deg
/gate/tapaportamuestra/placement/setTranslation 0. -99.75 0. mm
/gate/tapaportamuestra/vis/forceWireframe

#====================
# CONTENEDOR DE MUESTRA 
#====================
/gate/world/daughters/name contenedormuestra
/gate/world/daughters/insert cylinder
/gate/contenedormuestra/setMaterial PVC
/gate/contenedormuestra/vis/setColor cyan
/gate/contenedormuestra/geometry/setRmax 50.97 mm
/gate/contenedormuestra/geometry/setRmin 50.47 mm
/gate/contenedormuestra/geometry/setHeight 129.5 mm
/gate/contenedormuestra/placement/setRotationAxis 1 0 0
/gate/contenedormuestra/placement/setRotationAngle 90 deg
/gate/contenedormuestra/vis/forceWireframe

#====================
# TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapacontenedorsup
/gate/world/daughters/insert cylinder
/gate/tapacontenedorsup/setMaterial PVC
/gate/tapacontenedorsup/vis/setColor cyan
/gate/tapacontenedorsup/geometry/setRmax 62.63 mm
/gate/tapacontenedorsup/geometry/setRmin 61.63 mm
/gate/tapacontenedorsup/geometry/setHeight 20.8 mm
/gate/tapacontenedorsup/placement/setRotationAxis 1 0 0
/gate/tapacontenedorsup/placement/setRotationAngle 90 deg
/gate/tapacontenedorsup/placement/setTranslation 0. 75.15 0. mm
/gate/tapacontenedorsup/vis/forceWireframe

#====================
# TAPA PARA LA TAPA CONTENEDORMUESTRA (Parte superior) 
#====================
/gate/world/daughters/name tapasup
/gate/world/daughters/insert cylinder
/gate/tapasup/setMaterial PVC
/gate/tapasup/vis/setColor cyan
/gate/tapasup/geometry/setRmax 62.63 mm
/gate/tapasup/geometry/setRmin 0. mm
/gate/tapasup/geometry/setHeight 0.2 mm
/gate/tapasup/placement/setRotationAxis 1 0 0
/gate/tapasup/placement/setRotationAngle 90 deg
/gate/tapasup/placement/setTranslation 0. 64.76 0. mm
/gate/tapasup/vis/forceWireframe

#====================
# TAPA CONTENEDORMUESTRA (Parte inferior)
#====================
/gate/world/daughters/name tapacontenedormuestra
/gate/world/daughters/insert cylinder
/gate/tapacontenedormuestra/setMaterial PVC
/gate/tapacontenedormuestra/vis/setColor cyan
/gate/tapacontenedormuestra/geometry/setRmax 50.97 mm
/gate/tapacontenedormuestra/geometry/setRmin 0. mm
/gate/tapacontenedormuestra/geometry/setHeight 0.5 mm
/gate/tapacontenedormuestra/placement/setRotationAxis 1 0 0
/gate/tapacontenedormuestra/placement/setRotationAngle 90 deg
/gate/tapacontenedormuestra/placement/setTranslation 0. -64.75 0. mm
/gate/tapacontenedormuestra/vis/forceWireframe

#====================
# SOPORTE DE TUBOS (con agujeros) 
#====================
/gate/world/daughters/name soportetubos
/gate/world/daughters/insert cylinder
/gate/soportetubos/setMaterial Polypropilene
/gate/soportetubos/vis/setColor red
/gate/soportetubos/geometry/setRmax 50.965 mm
/gate/soportetubos/geometry/setRmin 0. mm
/gate/soportetubos/geometry/setHeight 25. mm
/gate/soportetubos/placement/setRotationAxis 1 0 0
/gate/soportetubos/placement/setRotationAngle 90 deg
/gate/soportetubos/placement/setTranslation 0. -12.5 0. mm
/gate/soportetubos/vis/forceWireframe

#====================
#CIRCULO MEDIO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulomedio
/gate/world/daughters/insert cylinder
/gate/circulomedio/setMaterial Polypropilene  
/gate/circulomedio/vis/setColor red           
/gate/circulomedio/geometry/setRmax 9.6 mm
/gate/circulomedio/geometry/setRmin 9.55 mm
/gate/circulomedio/geometry/setHeight 25. mm
/gate/circulomedio/placement/setRotationAxis 1 0 0
/gate/circulomedio/placement/setRotationAngle 90 deg
/gate/circulomedio/placement/setTranslation 0. -12.5 0. mm
/gate/circulomedio/vis/forceWireframe              
/gate/circulomedio/vis/setVisible true

#====================
#CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circuloexterno
/gate/world/daughters/insert cylinder
/gate/circuloexterno/setMaterial Polypropilene  
/gate/circuloexterno/vis/setColor red           
/gate/circuloexterno/geometry/setRmax 9.6 mm
/gate/circuloexterno/geometry/setRmin 9.55 mm
/gate/circuloexterno/geometry/setHeight 25. mm
/gate/circuloexterno/placement/setRotationAxis 1 0 0
/gate/circuloexterno/placement/setRotationAngle 90 deg
/gate/circuloexterno/placement/setTranslation 39. -12.5 0. mm
/gate/circuloexterno/vis/forceWireframe              

#====================
# REPEAT-CIRCULO EXTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circuloexterno/repeaters/insert ring
/gate/circuloexterno/ring/setRepeatNumber 12
/gate/circuloexterno/ring/setPoint1 0. 1. 0. mm
/gate/circuloexterno/ring/setPoint2 0. 0. 0. mm
/gate/circuloexterno/ring/disableAutoRotation

#====================
#CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/world/daughters/name circulointerno
/gate/world/daughters/insert cylinder
/gate/circulointerno/setMaterial Polypropilene  
/gate/circulointerno/vis/setColor red           
/gate/circulointerno/geometry/setRmax 9.6 mm
/gate/circulointerno/geometry/setRmin 9.55 mm
/gate/circulointerno/geometry/setHeight 25. mm
/gate/circulointerno/placement/setRotationAxis 1 0 0
/gate/circulointerno/placement/setRotationAngle 90 deg
/gate/circulointerno/placement/setTranslation 18.5 -12.5 11. mm
/gate/circulointerno/vis/forceWireframe              

#====================
# REPEAT-CIRCULO INTERNO DEL SOPORTE DE TUBOS
#====================
/gate/circulointerno/repeaters/insert ring
/gate/circulointerno/ring/setRepeatNumber 6
/gate/circulointerno/ring/setPoint1 0. 1. 0. mm
/gate/circulointerno/ring/setPoint2 0. 0. 0. mm
/gate/circulointerno/ring/disableAutoRotation

#====================
# SOPORTE DE MADERA 1
#====================
/gate/world/daughters/name soportemadera1
/gate/world/daughters/insert cylinder
/gate/soportemadera1/setMaterial Wood
/gate/soportemadera1/vis/setColor yellow
/gate/soportemadera1/geometry/setRmax 55.5 mm
/gate/soportemadera1/geometry/setRmin 0. mm
/gate/soportemadera1/geometry/setHeight 9. mm
/gate/soportemadera1/placement/setRotationAxis 1 0 0
/gate/soportemadera1/placement/setRotationAngle 90 deg
/gate/soportemadera1/placement/setTranslation 0. -69.25 0. mm
/gate/soportemadera1/vis/forceWireframe

#====================
# SOPORTE DE MADERA 2
#====================
/gate/world/daughters/name soportemadera2
/gate/world/daughters/insert box
/gate/soportemadera2/setMaterial Wood
/gate/soportemadera2/vis/setColor yellow
/gate/soportemadera2/geometry/setXLength 30. mm
/gate/soportemadera2/geometry/setYLength 30. mm
/gate/soportemadera2/geometry/setZLength 15. mm
/gate/soportemadera2/placement/setRotationAxis 1 0 0
/gate/soportemadera2/placement/setRotationAngle 90 deg
/gate/soportemadera2/placement/setTranslation 0. -81.5 0. mm
/gate/soportemadera2/vis/forceWireframe

#====================
# SOPORTE DE MADERA 3
#====================
/gate/world/daughters/name soportemadera3
/gate/world/daughters/insert cylinder
/gate/soportemadera3/setMaterial Wood
/gate/soportemadera3/vis/setColor yellow
/gate/soportemadera3/geometry/setRmax 55.5 mm
/gate/soportemadera3/geometry/setRmin 0. mm
/gate/soportemadera3/geometry/setHeight 9. mm
/gate/soportemadera3/placement/setRotationAxis 1 0 0
/gate/soportemadera3/placement/setRotationAngle 90 deg
/gate/soportemadera3/placement/setTranslation 0. -93.45 0. mm
/gate/soportemadera3/vis/forceWireframe

#====================
# SYSTEM - scanner (tubo Fricke)
#====================
/gate/world/daughters/name scanner
/gate/world/daughters/insert cylinder
/gate/scanner/setMaterial Air
/gate/scanner/vis/setColor yellow
/gate/scanner/geometry/setRmax 9.55 mm
/gate/scanner/geometry/setRmin 0. mm
/gate/scanner/geometry/setHeight 107.5 mm
/gate/scanner/placement/setRotationAxis 1 0 0
/gate/scanner/placement/setRotationAngle 90 deg

#====================
#TAPA- tapa del tubo 
#====================
/gate/scanner/daughters/name tapa
/gate/scanner/daughters/insert cylinder
/gate/tapa/setMaterial Polypropilene
/gate/tapa/vis/setColor white
/gate/tapa/geometry/setRmax 9.5 mm
/gate/tapa/geometry/setRmin 7.5 mm
/gate/tapa/geometry/setHeight 15.5 mm
/gate/tapa/placement/setTranslation 0 0 -44 mm
/gate/tapa/vis/forceWireframe

#====================
#TUBO FRICKE
#====================
/gate/scanner/daughters/name tubo
/gate/scanner/daughters/insert cylinder
/gate/tubo/setMaterial Glass
/gate/tubo/vis/setColor gray
/gate/tubo/geometry/setRmax 8.5 mm
/gate/tubo/geometry/setRmin 7.5 mm
/gate/tubo/geometry/setHeight 87. mm
/gate/tubo/placement/setTranslation 0 0 9.7 mm
/gate/tubo/vis/forceWireframe

#====================
#SOLUCIÓN ACUOSA FRICKE (detector sensible) (la altura 56.74 mm es acorcde a Volumen de 10 mL de agua)
#====================
/gate/tubo/daughters/name aguafricke
/gate/tubo/daughters/insert cylinder
/gate/aguafricke/setMaterial Water
/gate/aguafricke/vis/setColor blue
/gate/aguafricke/geometry/setRmax 7.49 mm
/gate/aguafricke/geometry/setRmin 0. mm
/gate/aguafricke/geometry/setHeight 56.74 mm
/gate/aguafricke/placement/setTranslation 0 0 15. mm
/gate/aguafricke/vis/forceWireframe

#====================
#ATTACH VOLUMES TO A SYSTEM
#====================
/gate/systems/scanner/level1/attach tapa
/gate/systems/scanner/level2/attach tubo
/gate/systems/scanner/level3/attach aguafricke

#====================
#DEFINE A SENSITIVE DETECTOR
#====================
/gate/aguafricke/attachCrystalSD

#====================
#GEOMETRY-Parte superior RACK (sin agujeros)
#====================
/gate/world/daughters/name racksup
/gate/world/daughters/insert cylinder
/gate/racksup/setMaterial StainlessSteel  
/gate/racksup/vis/setColor gray           
/gate/racksup/geometry/setRmax 85.5 mm
/gate/racksup/geometry/setRmin 75.5 mm
/gate/racksup/geometry/setHeight 1. mm
/gate/racksup/placement/setRotationAxis 1 0 0
/gate/racksup/placement/setRotationAngle 90 deg
/gate/racksup/placement/setTranslation 0. 101. 0. mm
/gate/racksup/vis/forceWireframe              
/gate/racksup/vis/setVisible true

#====================
#GEOMETRY-Parte inferior RACK (sin agujeros)
#====================
/gate/world/daughters/name rackinf
/gate/world/daughters/insert cylinder
/gate/rackinf/setMaterial StainlessSteel  
/gate/rackinf/vis/setColor gray           
/gate/rackinf/geometry/setRmax 85.5 mm
/gate/rackinf/geometry/setRmin 75.5 mm
/gate/rackinf/geometry/setHeight 1. mm
/gate/rackinf/placement/setRotationAxis 1 0 0
/gate/rackinf/placement/setRotationAngle 90 deg
/gate/rackinf/placement/setTranslation 0. -101. 0. mm
/gate/rackinf/vis/forceWireframe              
   
#====================
# FIRST LEVEL OF RACK - lapiz
#====================
/gate/world/daughters/name lapiz
/gate/world/daughters/insert cylinder
/gate/lapiz/setMaterial StainlessSteel
/gate/lapiz/placement/setTranslation 80.5 0. 0. mm
/gate/lapiz/vis/setColor gray
/gate/lapiz/geometry/setRmax 5. mm
/gate/lapiz/geometry/setRmin 4.99 mm
/gate/lapiz/geometry/setHeight 202. mm
/gate/lapiz/placement/setRotationAxis 1 0 0
/gate/lapiz/placement/setRotationAngle 90 deg
/gate/lapiz/vis/forceSolid

#====================
# REPEAT-lapiz se tiene 16 lapices
#====================
/gate/lapiz/repeaters/insert ring
/gate/lapiz/ring/setRepeatNumber 16
/gate/lapiz/ring/setPoint1 0. 1. 0. mm
/gate/lapiz/ring/setPoint2 0. 0. 0. mm
/gate/lapiz/ring/disableAutoRotation
/gate/lapiz/vis/forceSolid

#====================
#PHYSICS PROCESSES
#====================
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/addProcess RadioactiveDecay
/gate/physics/processList Enabled 
/gate/physics/processList Initialized

#====================
#INITIALIZE
#====================
/gate/run/initialize

#====================
#ADDER
#====================
#Para VGATE 9.1
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid

#Para VGATE9.3
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert adder
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/adder/positionPolicy energyWeightedCentroid

#====================
#READOUT
#====================
#Para VGATE 9.1
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2 #Agrupa hits a nivel del "tubo" (level 2)

#Para VGATE9.3
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert readout
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/readout/setDepth 2 #Agrupa hits a nivel del "tubo" (level 2)


#====================
#ENERGY BLURRING #VGate 9.1 (se utiliza la energia promedia entre las dos energías 1173.228 y 1332.492 keV)
#====================
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.015
/gate/digitizer/Singles/blurring/setEnergyOfReference 1252.86 keV

#====================
#ENERGY RESOLUTION #VGate 9.3 (Antes ENERGY BLURRING)(se utiliza la energia promedia entre las dos energías 1173.228 y 1332.492 keV)
#====================
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyResolution
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/fwhm 0.015
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyResolution/energyOfReference 1252.86 keV

#====================
#ENERGY WINDOW #VGATE 9.1
#====================
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 0. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 2000. keV

#====================
#ENERGY FRAMING #VGATE 9.3 (Previously Thresholder and Upholder)
#====================
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/insert energyFraming
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMin 0. keV
#/gate/digitizerMgr/aguafricke/SinglesDigitizer/Singles/energyFraming/setMax 2000. keV

#====================
#Actividad total de fuente 07/03/2023=119.20 Ci, como son 16 lapices la actividad por cada lapiz = 7.45 Ci
#====================

#====================
#SOURCE 1 (Co60 con espectro discreto desde archivo) (4.8e+06 es el limite que me quede antes de killed)
#====================
/gate/source/addSource SourceCo601 gps
/gate/source/SourceCo601/setActivity 7.45 Ci
/gate/source/SourceCo601/setForcedUnstableFlag false

#====================
#POSITION 
#====================
/gate/source/SourceCo601/gps/centre 80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo601/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo601/gps/type Volume
/gate/source/SourceCo601/gps/shape Cylinder
/gate/source/SourceCo601/gps/radius 4.985 mm
/gate/source/SourceCo601/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo601/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo601/gps/energytype UserSpectrum
/gate/source/SourceCo601/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE 
#====================
/gate/source/SourceCo601/visualize 10000 green 20


#====================
#REPEAT SOURCE 16 TIMES EN CADA LAPIZ
#====================
#====================
#SOURCE 2 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo602 gps
/gate/source/SourceCo602/setActivity 7.45 Ci
/gate/source/SourceCo602/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo602/gps/centre 74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo602/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo602/gps/type Volume
/gate/source/SourceCo602/gps/shape Cylinder
/gate/source/SourceCo602/gps/radius 4.985 mm
/gate/source/SourceCo602/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo602/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo602/gps/energytype UserSpectrum
/gate/source/SourceCo602/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo602/visualize 10000 green 20


#====================
#SOURCE 3 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo603 gps
/gate/source/SourceCo603/setActivity 7.45 Ci
/gate/source/SourceCo603/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo603/gps/centre 56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo603/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo603/gps/type Volume
/gate/source/SourceCo603/gps/shape Cylinder
/gate/source/SourceCo603/gps/radius 4.985 mm
/gate/source/SourceCo603/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo603/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo603/gps/energytype UserSpectrum
/gate/source/SourceCo603/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo603/visualize 10000 green 20


#====================
#SOURCE 4 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo604 gps
/gate/source/SourceCo604/setActivity 7.45 Ci
/gate/source/SourceCo604/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo604/gps/centre 30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo604/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo604/gps/type Volume
/gate/source/SourceCo604/gps/shape Cylinder
/gate/source/SourceCo604/gps/radius 4.985 mm
/gate/source/SourceCo604/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo604/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo604/gps/energytype UserSpectrum
/gate/source/SourceCo604/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo604/visualize 10000 green 20

#====================
#SOURCE 5 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo605 gps
/gate/source/SourceCo605/setActivity 7.45 Ci
/gate/source/SourceCo605/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo605/gps/centre 0. 0. 80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo605/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo605/gps/type Volume
/gate/source/SourceCo605/gps/shape Cylinder
/gate/source/SourceCo605/gps/radius 4.985 mm
/gate/source/SourceCo605/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo605/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo605/gps/mintheta 0. deg
/gate/source/SourceCo605/gps/maxtheta 180. deg
/gate/source/SourceCo605/gps/minphi 0. deg
/gate/source/SourceCo605/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo605/gps/energytype UserSpectrum
/gate/source/SourceCo605/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo605/visualize 10000 green 20

#====================
#SOURCE 6 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo606 gps
/gate/source/SourceCo606/setActivity 7.45 Ci
/gate/source/SourceCo606/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo606/gps/centre -30.8 0. 74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo606/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo606/gps/type Volume
/gate/source/SourceCo606/gps/shape Cylinder
/gate/source/SourceCo606/gps/radius 4.985 mm
/gate/source/SourceCo606/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo606/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo606/gps/energytype UserSpectrum
/gate/source/SourceCo606/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo606/visualize 10000 green 20

#====================
#SOURCE 7 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo607 gps
/gate/source/SourceCo607/setActivity 7.45 Ci
/gate/source/SourceCo607/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo607/gps/centre -56.9 0. 56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo607/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo607/gps/type Volume
/gate/source/SourceCo607/gps/shape Cylinder
/gate/source/SourceCo607/gps/radius 4.985 mm
/gate/source/SourceCo607/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo607/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo607/gps/energytype UserSpectrum
/gate/source/SourceCo607/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo607/visualize 10000 green 20

#====================
#SOURCE 8 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo608 gps
/gate/source/SourceCo608/setActivity 7.45 Ci
/gate/source/SourceCo608/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo608/gps/centre -74.4 0. 30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo608/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo608/gps/type Volume
/gate/source/SourceCo608/gps/shape Cylinder
/gate/source/SourceCo608/gps/radius 4.985 mm
/gate/source/SourceCo608/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo608/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo608/gps/energytype UserSpectrum
/gate/source/SourceCo608/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo608/visualize 10000 green 20

#====================
#SOURCE 9 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo609 gps
/gate/source/SourceCo609/setActivity 7.45 Ci
/gate/source/SourceCo609/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo609/gps/centre -80.5 0. 0. mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo609/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo609/gps/type Volume
/gate/source/SourceCo609/gps/shape Cylinder
/gate/source/SourceCo609/gps/radius 4.985 mm
/gate/source/SourceCo609/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo609/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo609/gps/mintheta 0. deg
/gate/source/SourceCo609/gps/maxtheta 180. deg
/gate/source/SourceCo609/gps/minphi 0. deg
/gate/source/SourceCo609/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo609/gps/energytype UserSpectrum
/gate/source/SourceCo609/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo609/visualize 10000 green 20

#====================
#SOURCE 10 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6010 gps
/gate/source/SourceCo6010/setActivity 7.45 Ci
/gate/source/SourceCo6010/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6010/gps/centre -74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6010/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6010/gps/type Volume
/gate/source/SourceCo6010/gps/shape Cylinder
/gate/source/SourceCo6010/gps/radius 4.985 mm
/gate/source/SourceCo6010/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6010/gps/angtype iso

#====================
#SET MIN AND MAX EMISSION ANGLES
#==================== 
/gate/source/SourceCo6010/gps/mintheta 0. deg
/gate/source/SourceCo6010/gps/maxtheta 180. deg
/gate/source/SourceCo6010/gps/minphi 0. deg
/gate/source/SourceCo6010/gps/maxphi 360. deg
/gate/source/list

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6010/gps/energytype UserSpectrum
/gate/source/SourceCo6010/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6010/visualize 10000 green 20

#====================
#SOURCE 11 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6011 gps
/gate/source/SourceCo6011/setActivity 7.45 Ci
/gate/source/SourceCo6011/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6011/gps/centre -56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6011/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6011/gps/type Volume
/gate/source/SourceCo6011/gps/shape Cylinder
/gate/source/SourceCo6011/gps/radius 4.985 mm
/gate/source/SourceCo6011/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6011/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6011/gps/energytype UserSpectrum
/gate/source/SourceCo6011/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6011/visualize 10000 green 20

#====================
#SOURCE 12 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6012 gps
/gate/source/SourceCo6012/setActivity 7.45 Ci
/gate/source/SourceCo6012/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6012/gps/centre -30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6012/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6012/gps/type Volume
/gate/source/SourceCo6012/gps/shape Cylinder
/gate/source/SourceCo6012/gps/radius 4.985 mm
/gate/source/SourceCo6012/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6012/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6012/gps/energytype UserSpectrum
/gate/source/SourceCo6012/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6012/visualize 10000 green 20

#====================
#SOURCE 13 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6013 gps
/gate/source/SourceCo6013/setActivity 7.45 Ci
/gate/source/SourceCo6013/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6013/gps/centre 0. 0. -80.5 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6013/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6013/gps/type Volume
/gate/source/SourceCo6013/gps/shape Cylinder
/gate/source/SourceCo6013/gps/radius 4.985 mm
/gate/source/SourceCo6013/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6013/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6013/gps/energytype UserSpectrum
/gate/source/SourceCo6013/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6013/visualize 10000 green 20

#====================
#SOURCE 14 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6014 gps
/gate/source/SourceCo6014/setActivity 7.45 Ci
/gate/source/SourceCo6014/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6014/gps/centre 30.8 0. -74.4 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6014/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6014/gps/type Volume
/gate/source/SourceCo6014/gps/shape Cylinder
/gate/source/SourceCo6014/gps/radius 4.985 mm
/gate/source/SourceCo6014/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6014/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6014/gps/energytype UserSpectrum
/gate/source/SourceCo6014/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6014/visualize 10000 green 20

#====================
#SOURCE 15 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6015 gps
/gate/source/SourceCo6015/setActivity 7.45 Ci
/gate/source/SourceCo6015/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6015/gps/centre 56.9 0. -56.9 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6015/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6015/gps/type Volume
/gate/source/SourceCo6015/gps/shape Cylinder
/gate/source/SourceCo6015/gps/radius 4.985 mm
/gate/source/SourceCo6015/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6015/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6015/gps/energytype UserSpectrum
/gate/source/SourceCo6015/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6015/visualize 10000 green 20

#====================
#SOURCE 16 (Co60 con espectro discreto desde archivo)
#====================
/gate/source/addSource SourceCo6016 gps
/gate/source/SourceCo6016/setActivity 7.45 Ci
/gate/source/SourceCo6016/setForcedUnstableFlag false

#====================
#POSITION
#====================
/gate/source/SourceCo6016/gps/centre 74.4 0. -30.8 mm

#====================
#PARTICLE
#====================
/gate/source/SourceCo6016/gps/particle gamma

#====================
#TYPE
#====================
/gate/source/SourceCo6016/gps/type Volume
/gate/source/SourceCo6016/gps/shape Cylinder
/gate/source/SourceCo6016/gps/radius 4.985 mm
/gate/source/SourceCo6016/gps/halfy 100. mm

#====================
#SET ANGULAR DISTRIBUITION
#====================
/gate/source/SourceCo6016/gps/angtype iso

#====================
#SET ENERGY DISTRIBUTION
#====================
/gate/source/SourceCo6016/gps/energytype UserSpectrum
/gate/source/SourceCo6016/gps/setSpectrumFile DiscreteSpectrumCo60.txt

#====================
#VISUALIZATION SOURCE
#==================== 
/gate/source/SourceCo6016/visualize 10000 green 20

#====================
#ASCII OUTPUT FORMAT
#====================
/gate/output/ascii/enable
/gate/output/ascii/setFileName detector1
/gate/output/ascii/setOutFileHitsFlag 0
/gate/output/ascii/setOutFileSinglesFlag 1

#====================
#ROOT OUTPUT FORMAT
#====================
/gate/output/root/enable
/gate/output/root/setFileName detector1
/gate/output/root/setRootSinglesFlag 1

#====================
#TIME SLICE
#====================
/gate/application/setTimeSlice     30. s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      3600. s

#====================
#SEED 
#====================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed default
/gate/random/verbose 0

#====================
#START ACQUISITION
#====================
/gate/application/start





